name: Mirror

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git remote add mirror https://x-access-token:${{ secrets.ORG_REPO_TOKEN }}@github.com/gsp26sap20/attachments-frontend.git
          git push mirror main --force
