name: Mirror

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git remote set-url mirror https://x-access-token:${{ secrets.ORG_REPO_TOKEN }}@${{ vars.ORG_REPO_URL }} \
          || git remote add mirror https://x-access-token:${{ secrets.ORG_REPO_TOKEN }}@${{ vars.ORG_REPO_URL }}

          git push mirror main --force
